name: Java CI

on:
  push:
    branches: [ main, testng, junit4, junit5, junit-platform ]
  pull_request:
    branches: [ main, testng, junit4, junit5, junit-platform ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Make gradlew executable
      run: chmod +x gradlew

    - name: Run tests with Gradle
      run: |
        ./gradlew test --no-daemon --console=plain
